hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra
  searchpath:
    - pkg://navsim.planning.script.config.common
  job:
    chdir: False

defaults:
  - default_common
  - default_evaluation
  - default_train_val_test_log_split
  - agent: front_camera_agent
  - override train_test_split: mini
  - _self_

experiment_name: front_cam_mini
seed: 0

# Dataset
cache_path: ${oc.env:NAVSIM_EXP_ROOT}/training_cache
force_cache_computation: false
use_cache_without_dataset: false

# Dataloader
dataloader:
  params:
    batch_size: 32
    num_workers: 4
    pin_memory: true
    prefetch_factor: 2

# Trainer
trainer:
  params:
    max_epochs: 20
    check_val_every_n_epoch: 2
    val_check_interval: 1.0
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    accelerator: gpu
    strategy: auto
    precision: 16-mixed
    num_nodes: 1
    num_sanity_val_steps: 0
    fast_dev_run: false
    accumulate_grad_batches: 1
    gradient_clip_val: 0.0
    gradient_clip_algorithm: norm
    default_root_dir: ${output_dir}
